<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\tarkov.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.68.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Tarkov.Application.csproj" />
    <ProjectReference Include="..\Tarkov.Infrastructure\Tarkov.Infrastructure.csproj" />
  </ItemGroup>

</Project>
